import * as path from 'node:path'
import { parseArgs } from 'node:util'

const { values, positionals } = parseArgs({
  args: Bun.argv,
  options: {
    help: { type: 'boolean' },
  },
  strict: true,
  allowPositionals: true,
})

const [, thisFile, weaponJsonPath] = positionals
const usageMessage = `Usage: bun ${path.relative(process.cwd(), thisFile)} [path to Weapon.json]`

if (values.help) {
  console.log('Import the Weapon.json file generated by VampireSurvivorsFiles')
  console.log(usageMessage)
  process.exit(0)
}

if (!weaponJsonPath) {
  console.error('Missing argument for path to Weapon.json')
  console.error(usageMessage)
  process.exit(1)
}

const file = Bun.file(weaponJsonPath)
const json = await file.json()

for await (const id of Object.keys(json)) {
  json[id][0].id = id
}

Bun.write(file, JSON.stringify(json, null, 2))

export {}
