import * as Weapon from '@/weapon'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { parseArgs } from 'node:util'

const { values, positionals } = parseArgs({
  args: Bun.argv,
  options: {
    help: { type: 'boolean' },
  },
  strict: true,
  allowPositionals: true,
})

const [, thisFile] = positionals
const usageMessage = `Usage: bun ${path.relative(process.cwd(), thisFile)} [sourceDirectory] [targetDirectory]`

if (values.help) {
  console.log(
    'Import weapon sprite and icon images generated by VampireSurvivorsFiles',
  )
  console.log(usageMessage)
  process.exit(0)
}

let [, , sourceDirectory, targetDirectory = 'public'] = positionals

if (!sourceDirectory) {
  console.error('Missing `sourceDirectory` argument')
  console.error(usageMessage)
  process.exit(1)
}

sourceDirectory = path.resolve(process.cwd(), sourceDirectory)
console.log(`Resolved source directory path: ${sourceDirectory}`)

targetDirectory = path.resolve(process.cwd(), targetDirectory)
console.log(`Resolved target directory path: ${targetDirectory}`)

const spritesDirectory = path.join(targetDirectory, 'sprites')
if (!(await fs.exists(spritesDirectory))) {
  console.info(`Creating missing sprites directory: ${spritesDirectory}`)
  await fs.mkdir(spritesDirectory)
}

const iconsDirectory = path.join(targetDirectory, 'icons')
if (!(await fs.exists(iconsDirectory))) {
  console.info(`Creating missing icons directory: ${iconsDirectory}`)
  await fs.mkdir(iconsDirectory)
}

const imageGlob = new Bun.Glob('**/*.png')
const imageFiles = await Array.fromAsync(imageGlob.scan(sourceDirectory))
console.info(`Detected ${imageFiles.length} image files in source directory`)

const primaryWeaponEntries = Weapon.loadPrimaryWeaponEntries()
console.info(`Copying images for ${primaryWeaponEntries.length} weapons`)

for (const entry of primaryWeaponEntries) {
  let spriteSource = imageFiles.find((file) =>
    file.includes(`Sprite-${entry.id}.png`),
  )
  let iconSource = imageFiles.find((file) =>
    file.includes(`Icon-${entry.id}.png`),
  )

  if (!spriteSource || !iconSource) {
    console.warn(`Missing sprite and/or icon for ${entry.id}`)
    continue
  }

  console.info(`${entry.id}: Using frameName value ${entry.frameName}`)

  spriteSource = path.resolve(sourceDirectory, spriteSource)
  const spriteTarget = path.join(spritesDirectory, entry.frameName)
  console.info(
    `${entry.id}: Copying source sprite ${spriteSource} to ${spriteTarget}`,
  )
  await fs.copyFile(spriteSource, spriteTarget)

  iconSource = path.resolve(sourceDirectory, iconSource)
  const iconTarget = path.join(iconsDirectory, entry.frameName)
  console.info(
    `${entry.id}: Copying source icon ${iconSource} to ${iconTarget}`,
  )
  await fs.copyFile(iconSource, iconTarget)
}
