/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123IdChar125RouteImport } from './routes/{-$id}'

const Char123IdChar125Route = Char123IdChar125RouteImport.update({
  id: '/{-$id}',
  path: '/{-$id}',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$id}': typeof Char123IdChar125Route
}
export interface FileRoutesByTo {
  '/{-$id}': typeof Char123IdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$id}': typeof Char123IdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$id}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$id}'
  id: '__root__' | '/{-$id}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123IdChar125Route: typeof Char123IdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$id}': {
      id: '/{-$id}'
      path: '/{-$id}'
      fullPath: '/{-$id}'
      preLoaderRoute: typeof Char123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123IdChar125Route: Char123IdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
